files:
  - ".gitignore"  # include
  - ".github"
  - ".vscode"
  - "tests/conftest.py"
  - ".flake8"
  - ".pre-commit-config.yml"
  - ".pypirc"
  - "docs"
  - "src/README.md"
  - "CODE_OF_CONDUCT.md"
  - "LICENSE"
  - "README.md"
  - "SECURITY.md"
  - "SUPPORT.md"
  - "pyproject.toml"

  - "!.github/workflows/template-sync.yml"
  - "!.github/template-sync.yml"
  - "!src/python_project"
  - "!tests/test_methods.py"
