name: Python Publish Workflow
on:
  workflow_call:

jobs:
  publish:
    uses: microsoft/action-python/.github/workflows/publish.yml@0.7.2
    secrets:
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      TEST_PYPI_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD  }}
